#:schema node_modules/wrangler/config-schema.json
name = "cfw-canary"
main = "src/index.ts"
compatibility_date = "2024-09-19"
account_id = "08ba5098e9c73e48149a563333e7143a"
workers_dev = true
kv_namespaces = [
  { binding = "CANARY_NAMESPACE", id = "2db0fff107504a318082f8b070d140d5" }
]